name: Auto Merge Dependabot PRs
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - '*'
      - '!master'
      - '!main'
jobs:
  tests:
    runs-on: ubuntu-20.04
    # if: github.actor == 'dependabot' || github.actor == 'dependabot-preview'
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start
  
  auto-merge:
    needs: tests
    runs-on: ubuntu-20.04
    # if: success() && github.actor == 'dependabot' || github.actor == 'dependabot-preview'
    steps:
      - name: Merge pull request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pull_number = context.payload.pull_request.number;
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number
            });

      - name: Delete branch
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branch_name = context.payload.pull_request.head.ref;
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/' + branch_name
            });
