name: Tests
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - '*'
      - '!master'
      - '!main'
jobs:
  tests:
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/devskillshq/boilerplate-base-image:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install
        run: npm install
      - name: build
        run: npm run build
      - name: Start daemon
        run: npm run start &
      - name: Run tests
        run: npm run test
